main: me.Warper.main.Warper
name: Warper
author: CJM
version: 1.4
api-version: 1.14
description: Creates warps
commands:
  SetPrivateWarp:
    aliases:
    - spw
    usage: /<SetPrivateWarp> <WarpName> [Icon Material]
    description: Set's a private warp
  SetGlobalWarp:
    aliases:
    - sgw
    usage: /<SetGlobalWarp> <WarpName> [Icon Material]
  SetSpawnLocation:
    aliases:
    - ssl
    usage: /<SetSpawnLocation>
  RemoveSpawnLocation:
    aliases:
    - rsl
    usage: /<RemoveSpawnLocation>
  RemoveGlobalWarp:
    aliases:
    - rgw
    usage: /<RemoveGlobalWarp> <WarpName>
  RemovePrivateWarp:
    aliases:
    - rpw
    usage: /<RemovePrivateWarp> <WarpName>
  Warper:
    aliases:
    - w
    usage: /<Warper>
permissions:
  warper.setwarp.private:
    default: true
  warper.removewarp.private:
    default: true