main: me.Warper.main.Warper
name: Warper
author: CJM
version: 1.0
api-version: 1.13
description: Creates warps
commands:
   Warper:
      aliases: [w]
      usage: /<Warper> [command]
      description: Main command